### PR TITLE
Creating new project management folder and readme

### PR DESCRIPTION
**Pull request by EKaroune**
Please add in any files you think should be in the project management folder. 

Then we can add templates of these files.

### CODE REVIEW

**Comment by EKaroune** [comment]
I realised that I had just added to the main so have deleted our folder and put it in this branch so we can work on it together.

**Comment by malvikasharan** [comment]
@all-contributors please @EKaroune for idea and content

**Comment by malvikasharan** [comment]
https://github.com/all-contributors please @EKaroune for idea and doc

**Comment by malvikasharan** [comment]
@all-contributors please @EKaroune for idea and doc

**Comment by malvikasharan** [comment]
https://github.com/all-contributors please @EKaroune for ideas and doc

**Comment by malvikasharan** [comment]
@all-contributors please @EKaroune for ideas and doc

**Comment by malvikasharan** [comment]
@all-contributors please add @EKaroune for ideas and doc

**Comment by malvikasharan** [comment]
@all-contributors please add @vhellon as a contributor for ideas, doc

**Review by malvikasharan — APPROVED** [review]

**Pull request merged**
